apiVersion: v1
kind: Service
metadata:
  name: notification-service
spec:
  selector:
    app: notificationService
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8002
  type: LoadBalancer
