apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent-service-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: agent-service
  template:
    metadata:
      labels:
        app: agent-service
    spec:
      containers:
        - name: agent-service
          image: 924918964891.dkr.ecr.ap-southeast-1.amazonaws.com/agent-service:latest
          ports:
            - containerPort: 8000
