apiVersion: v1
kind: Service
metadata:
  name: integration-service
spec:
  selector:
    app: integrationService
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8001
  type: LoadBalancer
