name: Deploy Agent Service to EKS

on:
  push:
    branches: [main]
    paths:
      - "agent-service/**"
      - ".github/workflows/deploy-agent.yml"

jobs:
  deploy:
    name: Build & Deploy to EKS
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::445162103425:role/GitHubActionsEKSDeployRole
          role-session-name: github-eks-session
          aws-region: ap-southeast-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push Docker image
        env:
          ECR_REGISTRY: 445162103425.dkr.ecr.ap-southeast-2.amazonaws.com
          ECR_REPOSITORY: agent-service
          IMAGE_TAG: latest
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG ./agent-service
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --name moonagent-cluster --region ap-southeast-2

      - name: Deploy to EKS
        run: |
          kubectl rollout restart deployment agent-service-deployment
