name: Deploy Agent Service to EKS

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy to EKS
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ap-southeast-1
      ECR_REGISTRY: 924918964891.dkr.ecr.ap-southeast-1.amazonaws.com
      IMAGE_TAG: ${{ github.sha }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure Docker for ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push Docker image
        run: |
          docker build -t $ECR_REGISTRY/agent-service:$IMAGE_TAG ./agent-service
          docker push $ECR_REGISTRY/agent-service:$IMAGE_TAG

      - name: Set up kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${KUBECONFIG_B64}" | base64 --decode > $HOME/.kube/config
          chmod 600 $HOME/.kube/config
        env:
          KUBECONFIG_B64: ${{ secrets.KUBECONFIG_B64 }}

      - name: Verify cluster access
        run: kubectl get nodes

      - name: Deploy new image to agent-service
        run: |
          kubectl set image deployment/agent-service-deployment \
            agent-service=$ECR_REGISTRY/agent-service:$IMAGE_TAG
