name: Deploy Microservices to EKS

on:
  push:
    branches: [main]
    paths:
      - "agent-service/**"
      - "integration-service/**"
      - "notification-service/**"

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - name: agent-service
            path: agent-service
            port: 8000
            ecr: agent-service

          - name: integration-service
            path: integration-service
            port: 8001
            ecr: integration-service

          - name: notification-service
            path: notification-service
            port: 8002
            ecr: notification-service

    defaults:
      run:
        working-directory: ${{ matrix.path }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with: role-to-assume
